/**
 * MDX Content Loader
 *
 * Provides utilities for loading MDX content as React Server Components.
 * This eliminates the need for dangerouslySetInnerHTML by using Next.js MDX integration.
 *
 * Import maps are auto-generated by `pnpm content:manifest`.
 */

import type { ComponentType } from "react";
import type { ContentType, Locale } from "@/types/content.types";
import { getContentEntry } from "@/lib/content-manifest";
import { getContentLocaleCandidates } from "@/lib/content-locale-fallback";
import {
  pageImporters,
  postImporters,
  productImporters,
  type MDXContentModule,
} from "@/lib/mdx-importers.generated";

type ContentImporter = () => Promise<MDXContentModule>;

function getImportersForType(
  type: ContentType,
): Record<string, Record<string, ContentImporter>> {
  switch (type) {
    case "posts":
      return postImporters;
    case "pages":
      return pageImporters;
    case "products":
      return productImporters;
    default:
      return {};
  }
}

async function loadMDXContent(
  type: ContentType,
  locale: Locale,
  slug: string,
): Promise<MDXContentModule | null> {
  const importers = getImportersForType(type);
  let resolvedLocale: Locale | null = null;

  for (const candidateLocale of getContentLocaleCandidates(type, locale)) {
    const entry = getContentEntry(type, candidateLocale, slug);
    if (entry !== undefined) {
      resolvedLocale = candidateLocale;
      break;
    }
  }

  if (resolvedLocale === null) {
    return null;
  }

  const localeImporters = importers[resolvedLocale];

  if (localeImporters === undefined) {
    return null;
  }

  const importer = localeImporters[slug];

  if (importer === undefined) {
    return null;
  }

  try {
    return await importer();
  } catch {
    return null;
  }
}

export async function getMDXComponent(
  type: ContentType,
  locale: Locale,
  slug: string,
): Promise<ComponentType | null> {
  const mdxModule = await loadMDXContent(type, locale, slug);
  return mdxModule?.default ?? null;
}
