/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: node scripts/starter-checks.js content-manifest
 *
 * This file provides static import maps for MDX content.
 * To update, add/remove/rename content files and re-run the generator.
 */

import type { ComponentType } from 'react';

export interface MDXContentModule {
  default: ComponentType;
  frontmatter?: Record<string, unknown>;
}

type ContentImporter = () => Promise<MDXContentModule>;

export const postImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
  },
  zh: {
  },
};

export const pageImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
    'about': () => import('../../content/pages/en/about.mdx'),
    'contact': () => import('../../content/pages/en/contact.mdx'),
    'flood-barrier-materials-guide': () => import('../../content/pages/en/flood-barrier-materials-guide.mdx'),
    'flood-barrier-specifications': () => import('../../content/pages/en/flood-barrier-specifications.mdx'),
    'oem-wholesale': () => import('../../content/pages/en/oem-wholesale.mdx'),
    'privacy': () => import('../../content/pages/en/privacy.mdx'),
    'terms': () => import('../../content/pages/en/terms.mdx'),
    'warranty': () => import('../../content/pages/en/warranty.mdx'),
  },
  zh: {
  },
};

export const productImporters: Record<string, Record<string, ContentImporter>> = {
  en: {
  },
  zh: {
  },
};
