/**
 * MDX Content Loader
 *
 * Provides utilities for loading MDX content as React Server Components.
 * This eliminates the need for dangerouslySetInnerHTML by using Next.js MDX integration.
 *
 * Import maps are auto-generated by `pnpm content:manifest`.
 */

import type { ComponentType } from "react";
import type { ContentType, Locale } from "@/types/content.types";
import { getContentEntry } from "@/lib/content-manifest";
import {
  pageImporters,
  postImporters,
  productImporters,
  type MDXContentModule,
} from "@/lib/mdx-importers.generated";

type ContentImporter = () => Promise<MDXContentModule>;

function getImportersForType(
  type: ContentType,
): Record<string, Record<string, ContentImporter>> {
  switch (type) {
    case "posts":
      return postImporters;
    case "pages":
      return pageImporters;
    case "products":
      return productImporters;
    default:
      return {};
  }
}

async function loadMDXContent(
  type: ContentType,
  locale: Locale,
  slug: string,
): Promise<MDXContentModule | null> {
  const entry = getContentEntry(type, locale, slug);

  if (entry === undefined) {
    return null;
  }

  const importers = getImportersForType(type);
  const localeImporters = importers[locale];

  if (localeImporters === undefined) {
    return null;
  }

  const importer = localeImporters[slug];

  if (importer === undefined) {
    return null;
  }

  try {
    return await importer();
  } catch {
    return null;
  }
}

export async function getMDXComponent(
  type: ContentType,
  locale: Locale,
  slug: string,
): Promise<ComponentType | null> {
  const mdxModule = await loadMDXContent(type, locale, slug);
  return mdxModule?.default ?? null;
}
