import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const COMPONENT_GOVERNANCE_REGISTRY_PATH =
  "src/components/component-governance.registry.json";
const UI_COMPONENT_INDEX_PATH = "docs/design/组件索引.md";
const UI_COMPONENT_PLAYBOOK_PATH = "docs/design/组件使用手册.md";
const DESIGN_README_PATH = "docs/design/设计.md";

interface ComponentGovernanceRegistry {
  components: Record<string, ComponentGovernanceRegistryItem>;
  version: number;
}

interface ComponentGovernanceRegistryItem {
  avoidWhen: string;
  clientBoundary: string;
  radixLayer: string;
  story: string;
  surface: string;
  useWhen: string;
}

interface UiComponentIndexRow {
  avoidWhen: string;
  clientBoundary: string;
  componentName: string;
  radixLayer: string;
  surface: string;
  useWhen: string;
}

function readText(filePath: string): string {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- test reads fixed repo docs by relative path
  return readFileSync(filePath, "utf8");
}

function readRegistry(): ComponentGovernanceRegistry {
  return JSON.parse(
    readText(COMPONENT_GOVERNANCE_REGISTRY_PATH),
  ) as ComponentGovernanceRegistry;
}

function stripTableCell(value: string): string {
  return value.replace(/^`|`$/g, "").trim();
}

function parseUiComponentIndexRows(
  markdown: string,
): Map<string, UiComponentIndexRow> {
  const rows = new Map<string, UiComponentIndexRow>();

  for (const line of markdown.split("\n")) {
    if (!line.startsWith("| `")) {
      continue;
    }

    const cells = line
      .split("|")
      .slice(1, -1)
      .map((cell) => stripTableCell(cell.trim()));

    if (cells.length !== 6) {
      continue;
    }

    const [
      componentName,
      radixLayer,
      surface,
      clientBoundary,
      useWhen,
      avoidWhen,
    ] = cells;

    rows.set(componentName, {
      componentName,
      radixLayer,
      surface,
      clientBoundary,
      useWhen,
      avoidWhen,
    });
  }

  return rows;
}

describe("UI component registry docs index", () => {
  it("documents every registered UI primitive with exact row-level metadata", () => {
    const registry = readRegistry();
    const indexRows = parseUiComponentIndexRows(
      readText(UI_COMPONENT_INDEX_PATH),
    );
    const registryComponentNames = Object.keys(registry.components).sort();

    expect(indexRows.size).toBe(registryComponentNames.length);

    for (const componentName of registryComponentNames) {
      const component = registry.components[componentName];
      const row = indexRows.get(componentName);

      expect(row, `${componentName} row missing from index`).toBeDefined();
      expect(row?.radixLayer).toBe(component.radixLayer);
      expect(row?.surface).toBe(component.surface);
      expect(row?.clientBoundary).toBe(component.clientBoundary);
      expect(row?.useWhen).toBe(component.useWhen);
      expect(row?.avoidWhen).toBe(component.avoidWhen);
    }

    for (const componentName of indexRows.keys()) {
      expect(
        registry.components,
        `${componentName} appears in index but not registry`,
      ).toHaveProperty(componentName);
    }
  });

  it("links the registry index from UI reference docs", () => {
    const playbook = readText(UI_COMPONENT_PLAYBOOK_PATH);
    const designReadme = readText(DESIGN_README_PATH);

    expect(playbook).toContain("组件索引.md");
    expect(designReadme).toContain("组件索引.md");
  });

  it("describes itself as a maintained mirror instead of generated output", () => {
    const index = readText(UI_COMPONENT_INDEX_PATH);

    expect(index).toContain("maintained mirror");
    expect(index).toContain("durable component discovery source for agents");
    expect(index).toContain("Do not treat this file as generated output");
    expect(index).not.toContain("Generated by");
  });
});
