/**
 * API Error Codes
 *
 * Standardized error codes for all API responses.
 * These codes are stable identifiers for machine consumption.
 * Human-readable messages are handled by client-side i18n.
 *
 * Naming convention: CATEGORY_ACTION_DETAIL
 */

// ============================================
// Common Error Codes (used across multiple APIs)
// ============================================

export const API_ERROR_CODES = {
  // Rate limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // Authentication & Authorization
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Server errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // Request validation
  INVALID_JSON_BODY: "INVALID_JSON_BODY",
  INVALID_REQUEST: "INVALID_REQUEST",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  CONFIRMATION_REQUIRED: "CONFIRMATION_REQUIRED",
  INVALID_LOCALE_PARAMETER: "INVALID_LOCALE_PARAMETER",

  // ============================================
  // Subscribe API
  // ============================================
  SUBSCRIBE_SUCCESS: "SUBSCRIBE_SUCCESS",
  SUBSCRIBE_VALIDATION_EMAIL_REQUIRED: "SUBSCRIBE_VALIDATION_EMAIL_REQUIRED",
  SUBSCRIBE_VALIDATION_EMAIL_INVALID: "SUBSCRIBE_VALIDATION_EMAIL_INVALID",
  SUBSCRIBE_SECURITY_REQUIRED: "SUBSCRIBE_SECURITY_REQUIRED",
  SUBSCRIBE_SECURITY_FAILED: "SUBSCRIBE_SECURITY_FAILED",
  SUBSCRIBE_PROCESSING_ERROR: "SUBSCRIBE_PROCESSING_ERROR",

  // ============================================
  // Web Vitals API
  // ============================================
  WEB_VITALS_RECORDED: "WEB_VITALS_RECORDED",
  WEB_VITALS_INVALID_FORMAT: "WEB_VITALS_INVALID_FORMAT",
  WEB_VITALS_PROCESS_FAILED: "WEB_VITALS_PROCESS_FAILED",
  WEB_VITALS_RETRIEVE_FAILED: "WEB_VITALS_RETRIEVE_FAILED",
  WEB_VITALS_DELETED: "WEB_VITALS_DELETED",
  WEB_VITALS_DELETE_FAILED: "WEB_VITALS_DELETE_FAILED",

  // ============================================
  // i18n Analytics API
  // ============================================
  I18N_ANALYTICS_RECORDED: "I18N_ANALYTICS_RECORDED",
  I18N_ANALYTICS_INVALID_FORMAT: "I18N_ANALYTICS_INVALID_FORMAT",
  I18N_ANALYTICS_PROCESS_FAILED: "I18N_ANALYTICS_PROCESS_FAILED",
  I18N_ANALYTICS_RETRIEVE_FAILED: "I18N_ANALYTICS_RETRIEVE_FAILED",
  I18N_ANALYTICS_DELETED: "I18N_ANALYTICS_DELETED",
  I18N_ANALYTICS_DELETE_FAILED: "I18N_ANALYTICS_DELETE_FAILED",

  // ============================================
  // Monitoring Dashboard API
  // ============================================
  MONITORING_DATA_RECEIVED: "MONITORING_DATA_RECEIVED",
  MONITORING_INVALID_FORMAT: "MONITORING_INVALID_FORMAT",
  MONITORING_PROCESS_FAILED: "MONITORING_PROCESS_FAILED",
  MONITORING_RETRIEVE_FAILED: "MONITORING_RETRIEVE_FAILED",
  MONITORING_DELETED: "MONITORING_DELETED",
  MONITORING_DELETE_FAILED: "MONITORING_DELETE_FAILED",
  MONITORING_CONFIG_UPDATED: "MONITORING_CONFIG_UPDATED",
  MONITORING_CONFIG_INVALID: "MONITORING_CONFIG_INVALID",
  MONITORING_CONFIG_UPDATE_FAILED: "MONITORING_CONFIG_UPDATE_FAILED",

  // ============================================
  // Cache Invalidation API
  // ============================================
  CACHE_INVALIDATED: "CACHE_INVALIDATED",
  CACHE_LOCALE_REQUIRED: "CACHE_LOCALE_REQUIRED",
  CACHE_INVALID_DOMAIN: "CACHE_INVALID_DOMAIN",
  CACHE_INVALIDATION_FAILED: "CACHE_INVALIDATION_FAILED",

  // ============================================
  // Contact API
  // ============================================
  CONTACT_SUCCESS: "CONTACT_SUCCESS",
  CONTACT_VALIDATION_FAILED: "CONTACT_VALIDATION_FAILED",
  CONTACT_PROCESSING_ERROR: "CONTACT_PROCESSING_ERROR",
  CONTACT_STATS_ERROR: "CONTACT_STATS_ERROR",
  CONTACT_SUBMISSION_EXPIRED: "CONTACT_SUBMISSION_EXPIRED",

  // ============================================
  // Inquiry API
  // ============================================
  INQUIRY_SUCCESS: "INQUIRY_SUCCESS",
  INQUIRY_SECURITY_REQUIRED: "INQUIRY_SECURITY_REQUIRED",
  INQUIRY_SECURITY_FAILED: "INQUIRY_SECURITY_FAILED",
  INQUIRY_VALIDATION_FAILED: "INQUIRY_VALIDATION_FAILED",
  INQUIRY_PROCESSING_ERROR: "INQUIRY_PROCESSING_ERROR",

  // ============================================
  // Turnstile Verification API
  // ============================================
  TURNSTILE_SUCCESS: "TURNSTILE_SUCCESS",
  TURNSTILE_MISSING_TOKEN: "TURNSTILE_MISSING_TOKEN",
  TURNSTILE_VERIFICATION_FAILED: "TURNSTILE_VERIFICATION_FAILED",
  TURNSTILE_NETWORK_ERROR: "TURNSTILE_NETWORK_ERROR",
  TURNSTILE_NOT_CONFIGURED: "TURNSTILE_NOT_CONFIGURED",

  // ============================================
  // Generic Error (fallback)
  // ============================================
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
